name: shnatter
description: New Social Posting

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <=3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  dropdown_button2: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  extended_image: ^7.0.2
  http: ^0.13.5
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.15
  mvc_pattern: ^8.12.0
  provider: ^6.0.0
  url_launcher: ^6.1.6
  firebase_database: ^10.0.5
  cloud_firestore: ^4.1.0
  mobile_scanner: ^3.2.0
  flutter_svg: ^2.0.5
  custom_pop_up_menu: ^1.2.4
  material_floating_search_bar: ^0.3.7
  fl_chart: ^0.61.0
  crypto: ^3.0.2
  firebase_auth: ^4.6.1
  google_sign_in: ^6.1.0
  time_elapsed: ^0.2.6
  firebase_storage: ^11.0.4
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  universal_html: ^2.0.8
  mime: ^1.0.2
  emoji_picker_flutter: ^1.5.4
  font_awesome_flutter: ^10.2.1
  badges: ^3.0.2
  uuid: ^3.0.7
  cloud_functions: ^4.0.6
  flutter_window_close: ^0.2.2
  syncfusion_flutter_datagrid: ^21.1.39
  flutter_html: ^3.0.0-alpha.6
  firebase_core: ^2.13.0
  percent_indicator: ^4.2.2
  firebase_messaging: ^14.1.1
  rounded_loading_button: ^2.1.0
  otp: ^3.1.3
  pretty_qr_code: ^2.0.3
  clipboard: ^0.1.3
  animated_widgets: ^1.1.0
  roundcheckbox: ^2.0.5
  dotted_border: ^2.0.0+3
  just_audio: ^0.9.32

  file_picker: ^5.3.0
  flutter_sound: ^9.2.13
  flutter_otp_text_field: ^1.1.1
  otp_text_field: ^1.1.3
  firebase_phone_auth_handler: ^1.0.8
  pinput: ^2.2.30
  intl_phone_field: ^3.1.0
  easy_container: ^1.0.4
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  geoflutterfire2: ^2.3.14
  flutter_launcher_icons: ^0.13.1
  flutter_app_badger: ^1.5.0
  google_maps_flutter_web: ^0.4.0+8

dependency_overrides:
  intl: 0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
  #   - assets/images/svg/
  #   - assets/images/svg/logo.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-Regular.ttf
        - asset: assets/fonts/Hind-Medium.ttf
        - asset: assets/fonts/Hind-Bold.ttf
        - asset: assets/fonts/Hind-Light.ttf
        - asset:
            assets/fonts/Hind-SemiBold.ttf
            #style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
