name: Deploy Dev Functions
on: 
  workflow_dispatch:
jobs:
  deploy_functions:
    name: Deploy Functions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        cd functions
        npm install    
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: '1//09NaVvluAd3LbCgYIARAAGAkSNwF-L9IrrV5Q1ziHI4P_QLra8Aecw8eBqbN-Q_nwY871byeDPd1Tl1XApevwFzhfmWKfQExUJls'
        PROJECT_ID: shnatter-dev
