name: CI for Master
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_web:
    name: Build Shnatter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --public build/web
      env:
        FIREBASE_TOKEN: '1//0c2LK7NixkZPYCgYIARAAGAwSNwF-L9IrsY2z0GTmmDTaVr0c5vQQ7ePwVeDqY_IEK0Y4IpqtQbTVqbWZjsxSKQDYSQonC3vY0uA'
        PROJECT_ID: default
