name: Android Prod Build
on: 
  workflow_dispatch:
  #push:
  #  tags:
  #  - '*'
jobs:
  deploy_functions:
    name: Make Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    - name: Build Android App
      run: flutter build apk 
      # --flavor dev -t lib/main_dev.dart
      #run: flutter build appbundle --flavor dev -t lib/main_dev.dart
    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
          appId: 1:414573634624:android:8d5d0fc6f5db25902b6ba5          
          token: 1//09NaVvluAd3LbCgYIARAAGAkSNwF-L9IrrV5Q1ziHI4P_QLra8Aecw8eBqbN-Q_nwY871byeDPd1Tl1XApevwFzhfmWKfQExUJls
          groups: ts
          #file: 'build/app/outputs/flutter-apk/app-dev-release.apk'
          file: 'build/app/outputs/flutter-apk/app-release.apk'
          #file: 'build/app/outputs/bundle/devRelease/app-dev-release.aab'
    #- name: Release Apps
    #  uses: ncipollo/release-action@v1
    #  with:
    #     artifacts: 'build/app/outputs/flutter-apk/app-dev-release.apk'
    #     token: ${{ secrets.GITHUB_TOKEN }} 
    
